Neos:
  Flow:
    error:
      exceptionHandler:
        renderingGroups:
          notFoundExceptions:
            options:
              # Force static exception rendering.
              templatePathAndFilename: null
              viewClassName: Neos\FluidAdaptor\View\StandaloneView
          serverErrorExceptions:
            matchingStatusCodes: [ 500 ]
            options:
              logException: true

Netlogix:
  ErrorHandler:

    pages: []

#      'my-site':
#        -
#          dimensionPathSegment: 'en_US'
#          dimensions:
#            language: ['en_US', 'en']
#          matchingStatusCodes: [500]
#          source: '#550e8400-e29b-11d4-a716-446655440000'
#          destination: '${"/var/www/default/" + site + "/" + dimensions + "/500.html"}'
