Neos:
  Flow:
    error:
      exceptionHandler:
        renderingGroups:
          serverErrorExceptions:
            matchingStatusCodes: [ 500 ]
            options:
              logException: true
              viewOptions:
                templatePathAndFilename: 'resource://Neos.Flow/Private/Templates/Error/Default.html'

Netlogix:
  ErrorHandler:

    destination: '${"/var/www/default/" + site + "/" + dimensions + "/" + node + ".html"}'
