Neos:
  Flow:
    error:
      exceptionHandler:
        renderingGroups:
          serverErrorExceptions:
            matchingStatusCodes: [ 500 ]
            options:
              logException: true
              viewOptions:
                templatePathAndFilename: 'resource://Neos.Flow/Private/Templates/Error/Default.html'

Netlogix:
  ErrorHandler:

    pages: []

#      'my-site':
#        -
#          dimensionPathSegment: 'en_US'
#          dimensions:
#            language: ['en_US', 'en']
#          matchingStatusCodes: [500]
#          pathPrefixes: ['/some-prefix', '/some-other-prefix']
#          source: '#550e8400-e29b-11d4-a716-446655440000'
#          destination: '${"/var/www/default/" + site + "/" + dimensions + "/500.html"}'
